// <auto-generated />
namespace Cad.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Adicionadocampoparafuncionalidadedeesqueciemail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adicionadocampoparafuncionalidadedeesqueciemail));
        
        string IMigrationMetadata.Id
        {
            get { return "201708150023242_Adicionado campo para funcionalidade de esqueci email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
